version: "3.8"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8002:8080
    depends_on:
      - mysql_db
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_USER: user_name
      MYSQL_PASSWORD: root
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: first
      MYSQL_HOST: mysql_db
      MYSQL_USER: user_name
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root